In [1]:
import pandas as pd
import numpy as np
import csv

sales_2016 = pd.read_csv('./추정매출_2016.csv', encoding = 'cp949') # 2016년 추정매출 
sales_2017 = pd.read_csv('./추정매출_2017.csv', encoding = 'cp949') # 2017년 추정매출 
sales_2018 = pd.read_csv('./추정매출_2018.csv', encoding = 'cp949') # 2018년 추정매출 
sales_2019 = pd.read_csv('./추정매출_2019.csv', encoding = 'cp949') # 2019년 추정매출 
sales_2020 = pd.read_csv('./추정매출_2020.csv', encoding = 'cp949') # 2020년 추정매출

In [2]:
move = pd.read_csv('./추정유동인구.csv', encoding = 'cp949') # 유동인구 읽어오기
change = pd.read_csv('./상권.csv', encoding = 'cp949') # 상권변화 지표 읽어오기

/Users/wisebin/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
sales = pd.concat([sales_2016, sales_2017, sales_2018, sales_2019, sales_2020]) # 16~20 합치기
sales = sales[['기준_년_코드', '기준_분기_코드', '상권_구분_코드_명', 
               '상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명', '당월_매출_금액']] # 주요 컬럼 추출 
sales

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액
0,2016,1,골목상권,1000013,율곡로10길,CS300011,일반의류,27000000
1,2016,1,전통시장,1001271,동묘시장,CS300017,시계및귀금속,649744
2,2016,1,골목상권,1000447,증가로10길,CS300006,미곡판매,1856535
3,2016,1,전통시장,1001420,고척근린시장,CS300035,인테리어,152749
4,2016,1,골목상권,1000936,학동로38길,CS300014,신발,1000000
...,...,...,...,...,...,...,...,...
132316,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129
132317,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306
132318,2020,1,골목상권,1000001,계동길,CS100003,일식음식점,55484866
132319,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161
132320,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455

In [4]:
filter_value = {'전자상거래업':'전자','가전제품': '전자', '핸드폰' : '전자', '컴퓨터및주변장치판매': '전자'
               , '가전제품수리': '전자', '통신기기수리' : '전자', '가구' : '인테리어', '화초' : '인테리어', 
                '조명용품' : '인테리어', '예술품' : '인테리어', '인테리어' : '인테리어',
               '예술학원' : '교육', '외국어학원' : '교육', '일반교습학원' : '교육',
               '고시원': '주거', '여관' : '주거', '부동산중개업' : '주거', '건축물청소' : '주거',
                '섬유제품' : '패션', '시계및귀금속' : '패션', '가방' : '패션', '신발' : '패션', '일반의류' : '패션',
                '한복점' : '패션', '유아의류' : '패션', '패션' : '패션',
                '화장품' : '미용', '피부관리실' : '미용' , '네일숍' : '미용', '미용실' : '미용',
                '운동/경기용품': '취미', '스포츠클럽': '취미', '노래방': '취미', 'pc방': '취미', '골프연습장': '취미', 
                '당구장': '취미', '스포츠 강습': '취미', '자전거 및 기타운송장비': '취미', '볼링장': '취미', '악기': '취미','서적' : '취미',
                '비디오/서적임대': '취미', '반찬가게': '식품', '슈퍼마켓': '식품', '커피-음료': '식품', '분식전문점': '식품', 
                '패스트푸드점': '식품', '제과점': '식품', '양식음식점': '식품', '일식음식점': '식품', '중식음식점': '식품',
                '한식음식점': '식품', '육류판매': '식품', '호프-간이주점': '식품','치킨전문점': '식품', '청과상': '식품', 
                '수산물판매': '식품', '미곡판매': '식품', '의약품': '의료', '치과의원': '의료', '일반의원': '의료', 
                '의료기기': '의료', '한의원': '의료', '자동차수리': '자동차', 
                '자동차미용': '자동차', '자동차부품': '자동차', '중고차판매': '자동차','완구': '기타', '문구': '기타', 
                '안경': '기타', '편의점': '기타', '철물점': '기타', '애완동물': '기타', '여행사': '기타', '사진관': '기타', '세탁소' : '기타',
                '법무사사무소': '기타', '독서실': '기타', '세무사사무소': '기타', '주유소': '기타', '변호사사무소': '기타', '회계사사무소': '기타'}
# 업종 필터링 오브젝트 

sales["업종_분류"] = sales["서비스_업종_코드_명"].apply(lambda x: filter_value[x.lower()]) # 업종 필터링 컬럼 생성 
sales

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류
0,2016,1,골목상권,1000013,율곡로10길,CS300011,일반의류,27000000,패션
1,2016,1,전통시장,1001271,동묘시장,CS300017,시계및귀금속,649744,패션
2,2016,1,골목상권,1000447,증가로10길,CS300006,미곡판매,1856535,식품
3,2016,1,전통시장,1001420,고척근린시장,CS300035,인테리어,152749,인테리어
4,2016,1,골목상권,1000936,학동로38길,CS300014,신발,1000000,패션
...,...,...,...,...,...,...,...,...,...
132316,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129,식품
132317,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306,식품
132318,2020,1,골목상권,1000001,계동길,CS100003,일식음식점,55484866,식품
132319,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161,식품
132320,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455,식품

In [5]:
sales.index = sales['상권_코드'].map(str) + "_" + sales["서비스_업종_코드_명"].map(str) # 상권 코드와 업종 코드로 인덱스 생성 
sales

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류
1000013_일반의류,2016,1,골목상권,1000013,율곡로10길,CS300011,일반의류,27000000,패션
1001271_시계및귀금속,2016,1,전통시장,1001271,동묘시장,CS300017,시계및귀금속,649744,패션
1000447_미곡판매,2016,1,골목상권,1000447,증가로10길,CS300006,미곡판매,1856535,식품
1001420_인테리어,2016,1,전통시장,1001420,고척근린시장,CS300035,인테리어,152749,인테리어
1000936_신발,2016,1,골목상권,1000936,학동로38길,CS300014,신발,1000000,패션
...,...,...,...,...,...,...,...,...,...
1000001_제과점,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129,식품
1000001_양식음식점,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306,식품
1000001_일식음식점,2020,1,골목상권,1000001,계동길,CS100003,일식음식점,55484866,식품
1000001_중식음식점,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161,식품
1000001_한식음식점,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455,식품

In [6]:
s_19 = sales["기준_년_코드"] == 2019
s_20 = sales["기준_년_코드"] == 2020
s_1920 = pd.concat([sales[s_19], sales[s_20]]) # 매출 데이터에서 연도가 19, 20년인 데이터만 추출 
s_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류
1000985_예술학원,2019,1,골목상권,1000985,암사길,CS200003,예술학원,20061598,교육
1000267_노래방,2019,1,골목상권,1000267,돌곶이로8길,CS200037,노래방,510636,취미
1001445_섬유제품,2019,1,전통시장,1001445,영도시장,CS300027,섬유제품,4038928,패션
1000789_시계및귀금속,2019,1,골목상권,1000789,난곡로24길,CS300017,시계및귀금속,5085873,패션
1000930_일반교습학원,2019,1,골목상권,1000930,언주로81길,CS200001,일반교습학원,527027,교육
...,...,...,...,...,...,...,...,...,...
1000001_제과점,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129,식품
1000001_양식음식점,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306,식품
1000001_일식음식점,2020,1,골목상권,1000001,계동길,CS100003,일식음식점,55484866,식품
1000001_중식음식점,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161,식품
1000001_한식음식점,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455,식품

In [8]:
s_1920["개수"] = s_1920.groupby(s_1920.index).size()
s_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수
1000985_예술학원,2019,1,골목상권,1000985,암사길,CS200003,예술학원,20061598,교육,8
1000267_노래방,2019,1,골목상권,1000267,돌곶이로8길,CS200037,노래방,510636,취미,8
1001445_섬유제품,2019,1,전통시장,1001445,영도시장,CS300027,섬유제품,4038928,패션,6
1000789_시계및귀금속,2019,1,골목상권,1000789,난곡로24길,CS300017,시계및귀금속,5085873,패션,7
1000930_일반교습학원,2019,1,골목상권,1000930,언주로81길,CS200001,일반교습학원,527027,교육,4
...,...,...,...,...,...,...,...,...,...,...
1000001_제과점,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129,식품,8
1000001_양식음식점,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306,식품,8
1000001_일식음식점,2020,1,골목상권,1000001,계동길,CS100003,일식음식점,55484866,식품,7
1000001_중식음식점,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161,식품,8
1000001_한식음식점,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455,식품,8

In [314]:
is_all = s_1920["개수"] == 8 # 19, 20년도 모든 기간동안 존재하는 데이터만 추출 
s_1920 = s_1920[is_all]
s_1920.index =  s_1920['상권_코드'].map(str) + "_" + s_1920['기준_년_코드'].map(str) + "_" + s_1920['기준_분기_코드'].map(str)
s_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수
1000985_2019_1,2019,1,골목상권,1000985,암사길,CS200003,예술학원,20061598,교육,8
1000267_2019_1,2019,1,골목상권,1000267,돌곶이로8길,CS200037,노래방,510636,취미,8
1001001_2019_1,2019,1,골목상권,1001001,천중로39길,CS200005,스포츠 강습,22390312,취미,8
1001483_2019_1,2019,1,전통시장,1001483,암사종합시장,CS300008,수산물판매,1712543938,식품,8
1000612_2019_1,2019,1,골목상권,1000612,개봉로1길,CS300001,슈퍼마켓,42028959,식품,8
...,...,...,...,...,...,...,...,...,...,...
1000001_2020_1,2020,1,골목상권,1000001,계동길,CS100006,패스트푸드점,35752631,식품,8
1000001_2020_1,2020,1,골목상권,1000001,계동길,CS100005,제과점,257814129,식품,8
1000001_2020_1,2020,1,골목상권,1000001,계동길,CS100004,양식음식점,156728306,식품,8
1000001_2020_1,2020,1,골목상권,1000001,계동길,CS100002,중식음식점,25767161,식품,8
1000001_2020_1,2020,1,골목상권,1000001,계동길,CS100001,한식음식점,431442455,식품,8

In [315]:
sales = sales[sales["기준_년_코드"] !=2019]
sales = sales[sales["기준_년_코드"] !=2020]

In [316]:
sales["개수"] = sales.groupby(sales.index).size()
is_all = sales["개수"] == 12 # 16, 17, 18년도 모든 기간동안 존재하는 데이터만 추출 
s_1618 = sales[is_all]
s_1618.index =  s_1618['상권_코드'].map(str) + "_" + s_1618['기준_년_코드'].map(str) + "_" + s_1618['기준_분기_코드'].map(str)
s_1618

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수
1000013_2016_1,2016,1,골목상권,1000013,율곡로10길,CS300011,일반의류,27000000,패션,12
1001271_2016_1,2016,1,전통시장,1001271,동묘시장,CS300017,시계및귀금속,649744,패션,12
1000447_2016_1,2016,1,골목상권,1000447,증가로10길,CS300006,미곡판매,1856535,식품,12
1000316_2016_1,2016,1,골목상권,1000316,노해로23길,CS200005,스포츠 강습,19867446,취미,12
1000086_2016_1,2016,1,골목상권,1000086,효창원로39길,CS300035,인테리어,30672554,인테리어,12
...,...,...,...,...,...,...,...,...,...,...
1000732_2018_4,2018,4,골목상권,1000732,영신로9길,CS100002,중식음식점,208274869,식품,12
1001487_2018_4,2018,4,전통시장,1001487,천호시장,CS200008,한의원,35578749,의료,12
1000644_2018_4,2018,4,골목상권,1000644,디지털로32길,CS100008,분식전문점,849800508,식품,12
1001021_2018_4,2018,4,발달상권,1001021,가산디지털단지역_1,CS200007,치과의원,384299742,의료,12
1000994_2018_4,2018,4,골목상권,1000994,올림픽로71길,CS300011,일반의류,7041051,패션,12

In [317]:
move = move.rename(columns={'기준 년코드':'기준_년_코드'})
# 유동인구 데이터에서 필요 컬럼만 추출하고 14년도 15년도 데이터는 삭제 
move = move[['기준_년_코드', '기준_분기_코드', ' 상권_구분_코드', '상권_코드', '상권_코드_명', '총_유동인구_수']]
move = move[move["기준_년_코드"] !=2014]
move = move[move["기준_년_코드"] !=2015]
move

       기준_년_코드  기준_분기_코드  상권_구분_코드    상권_코드                 상권_코드_명  총_유동인구_수
0         2020         4         U  1001496             강남 마이스 관광특구     90836
1         2020         4         U  1001495                 잠실 관광특구   2956754
2         2020         4         U  1001494              종로?청계 관광특구   3738997
3         2020         4         U  1001493            동대문패션타운 관광특구   3058361
4         2020         4         U  1001492  명동 남대문 북창동 다동 무교동 관광특구   3569497
...        ...       ...       ...      ...                     ...       ...
29934     2016         1         A  1000005                    백석동길       139
29935     2016         1         A  1000004                     명륜길     65833
29936     2016         1         A  1000003                돈화문로11가길     63394
29937     2016         1         A  1000002                  난계로27길    159042
29938     2016         1         A  1000001                     계동길     76823

[29939 rows x 6 columns]

In [318]:
m_code = move.iloc[:, 3]
move.index = m_code.map(str)

m_19 = move["기준_년_코드"] == 2019
m_20 = move["기준_년_코드"] == 2020
m_1920 = pd.concat([move[m_19], move[m_20]]) # 유동인구 데이터에서 연도가 19, 20년인 데이터만 추출 

m_1920["개수"] = m_1920.groupby(m_1920.index).size()
is_all = m_1920["개수"] == 8 # 19, 20년도 모든 기간동안 존재하는 데이터만 추출 
m_1920 = m_1920[is_all]

m_1920.index =  m_1920['상권_코드'].map(str) +  "_" + m_1920['기준_년_코드'].map(str) + "_" + m_1920['기준_분기_코드'].map(str)
m_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_코드,상권_코드_명,총_유동인구_수,개수
1001496_2019_4,2019,4,U,1001496,강남 마이스 관광특구,130493,8
1001495_2019_4,2019,4,U,1001495,잠실 관광특구,3225556,8
1001494_2019_4,2019,4,U,1001494,종로?청계 관광특구,4917960,8
1001493_2019_4,2019,4,U,1001493,동대문패션타운 관광특구,3875197,8
1001492_2019_4,2019,4,U,1001492,명동 남대문 북창동 다동 무교동 관광특구,5278508,8
...,...,...,...,...,...,...,...
1000005_2020_1,2020,1,A,1000005,백석동길,178717,8
1000004_2020_1,2020,1,A,1000004,명륜길,623119,8
1000003_2020_1,2020,1,A,1000003,돈화문로11가길,178244,8
1000002_2020_1,2020,1,A,1000002,난계로27길,347131,8
1000001_2020_1,2020,1,A,1000001,계동길,336343,8

In [319]:
move = move[move["기준_년_코드"] !=2019]
move = move[move["기준_년_코드"] !=2020]

move["개수"] = move.groupby(move.index).size()
is_all = move["개수"] == 12 # 16, 17, 18년도 모든 기간동안 존재하는 데이터만 추출 
m_1618 = move[is_all]

m_1618.index =  m_1618['상권_코드'].map(str) + "_" + m_1618['기준_년_코드'].map(str) + "_" + m_1618['기준_분기_코드'].map(str)
m_1618

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_코드,상권_코드_명,총_유동인구_수,개수
1001496_2018_4,2018,4,U,1001496,강남 마이스 관광특구,56902,12
1001495_2018_4,2018,4,U,1001495,잠실 관광특구,1912079,12
1001494_2018_4,2018,4,U,1001494,종로?청계 관광특구,4524906,12
1001493_2018_4,2018,4,U,1001493,동대문패션타운 관광특구,2757199,12
1001492_2018_4,2018,4,U,1001492,명동 남대문 북창동 다동 무교동 관광특구,4905600,12
...,...,...,...,...,...,...,...
1000005_2016_1,2016,1,A,1000005,백석동길,139,12
1000004_2016_1,2016,1,A,1000004,명륜길,65833,12
1000003_2016_1,2016,1,A,1000003,돈화문로11가길,63394,12
1000002_2016_1,2016,1,A,1000002,난계로27길,159042,12
1000001_2016_1,2016,1,A,1000001,계동길,76823,12

In [320]:
# 상권변화 지표에서 14년도 15년도 데이터를 삭제 
change = change[change["기준_년_코드"] !=2014]
change = change[change["기준_년_코드"] !=2015]

c_code = change.iloc[:, 4]
change.index = c_code.map(str)
change

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
상권_코드,,,,,,,,,,,,
1001496,2020,4,U,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54
1001495,2020,4,U,관광특구,1001495,잠실 관광특구,LL,다이나믹,108,53,114,54
1001494,2020,4,U,관광특구,1001494,종로?청계 관광특구,HH,정체,152,73,114,54
1001493,2020,4,U,관광특구,1001493,동대문패션타운 관광특구,HH,정체,129,62,114,54
1001492,2020,4,U,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,HH,정체,154,64,114,54
...,...,...,...,...,...,...,...,...,...,...,...,...
1000005,2016,1,A,골목상권,1000005,백석동길,LL,다이나믹,77,47,96,48
1000004,2016,1,A,골목상권,1000004,명륜길,LH,상권확장,81,57,96,48
1000003,2016,1,A,골목상권,1000003,돈화문로11가길,HH,정체,105,48,96,48
1000002,2016,1,A,골목상권,1000002,난계로27길,HL,상권축소,113,40,96,48
1000001,2016,1,A,골목상권,1000001,계동길,LH,상권확장,89,53,96,48

In [321]:
c_19 = change["기준_년_코드"] == 2019
c_20 = change["기준_년_코드"] == 2020
c_1920 = pd.concat([change[c_19], change[c_20]]) # 유동인구 데이터에서 19년도 20년도 데이터만 추출 

c_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
상권_코드,,,,,,,,,,,,
1001496,2019,4,U,관광특구,1001496,강남 마이스 관광특구,HH,정체,119,61,110,54
1001495,2019,4,U,관광특구,1001495,잠실 관광특구,LL,다이나믹,105,53,110,54
1001494,2019,4,U,관광특구,1001494,종로?청계 관광특구,HH,정체,151,71,110,54
1001493,2019,4,U,관광특구,1001493,동대문패션타운 관광특구,HH,정체,121,61,110,54
1001492,2019,4,U,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,HH,정체,147,62,110,54
...,...,...,...,...,...,...,...,...,...,...,...,...
1000005,2020,1,A,골목상권,1000005,백석동길,LL,다이나믹,90,50,110,54
1000004,2020,1,A,골목상권,1000004,명륜길,LH,상권확장,81,56,110,54
1000003,2020,1,A,골목상권,1000003,돈화문로11가길,HH,정체,113,60,110,54
1000002,2020,1,A,골목상권,1000002,난계로27길,HL,상권축소,116,48,110,54
1000001,2020,1,A,골목상권,1000001,계동길,LH,상권확장,97,56,110,54

In [322]:
c_1920["개수"] = c_1920.groupby(c_1920.index).size()
is_all = c_1920["개수"] == 8 # 19, 20년도 모든 기간동안 존재하는 데이터만을 추출 
c_1920 = c_1920[is_all]

c_1920.index =  c_1920['상권_코드'].map(str) + "_" + c_1920['기준_년_코드'].map(str) + "_" + c_1920['기준_분기_코드'].map(str)
c_1920

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균,개수
1001496_2019_4,2019,4,U,관광특구,1001496,강남 마이스 관광특구,HH,정체,119,61,110,54,8
1001495_2019_4,2019,4,U,관광특구,1001495,잠실 관광특구,LL,다이나믹,105,53,110,54,8
1001494_2019_4,2019,4,U,관광특구,1001494,종로?청계 관광특구,HH,정체,151,71,110,54,8
1001493_2019_4,2019,4,U,관광특구,1001493,동대문패션타운 관광특구,HH,정체,121,61,110,54,8
1001492_2019_4,2019,4,U,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,HH,정체,147,62,110,54,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000005_2020_1,2020,1,A,골목상권,1000005,백석동길,LL,다이나믹,90,50,110,54,8
1000004_2020_1,2020,1,A,골목상권,1000004,명륜길,LH,상권확장,81,56,110,54,8
1000003_2020_1,2020,1,A,골목상권,1000003,돈화문로11가길,HH,정체,113,60,110,54,8
1000002_2020_1,2020,1,A,골목상권,1000002,난계로27길,HL,상권축소,116,48,110,54,8
1000001_2020_1,2020,1,A,골목상권,1000001,계동길,LH,상권확장,97,56,110,54,8

In [323]:
change = change[change["기준_년_코드"] !=2019]
change = change[change["기준_년_코드"] !=2020]

change["개수"] = change.groupby(change.index).size()
is_all = change["개수"] == 12 # 16, 17, 18년도 모든 기간동안 존재하는 데이터만 추출
c_1618 = change[is_all]

c_1618.index =  c_1618['상권_코드'].map(str) + "_" + c_1618['기준_년_코드'].map(str) + "_" + c_1618['기준_분기_코드'].map(str)
c_1618

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균,개수
1001496_2018_4,2018,4,U,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12
1001495_2018_4,2018,4,U,관광특구,1001495,잠실 관광특구,LH,상권확장,90,52,102,51,12
1001494_2018_4,2018,4,U,관광특구,1001494,종로?청계 관광특구,HH,정체,142,64,102,51,12
1001493_2018_4,2018,4,U,관광특구,1001493,동대문패션타운 관광특구,HH,정체,127,53,102,51,12
1001492_2018_4,2018,4,U,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,HH,정체,139,59,102,51,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000005_2016_1,2016,1,A,골목상권,1000005,백석동길,LL,다이나믹,77,47,96,48,12
1000004_2016_1,2016,1,A,골목상권,1000004,명륜길,LH,상권확장,81,57,96,48,12
1000003_2016_1,2016,1,A,골목상권,1000003,돈화문로11가길,HH,정체,105,48,96,48,12
1000002_2016_1,2016,1,A,골목상권,1000002,난계로27길,HL,상권축소,113,40,96,48,12
1000001_2016_1,2016,1,A,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12

In [326]:
sales_move_merge_1920 = pd.merge(s_1920, m_1920, left_index=True, right_index=True, how="inner")
sales_move_merge_1920 # 19, 20년도 추정매출과 유동인구 데이터에 inner join 적용

,기준_년_코드_x,기준_분기_코드_x,상권_구분_코드_명,상권_코드_x,상권_코드_명_x,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수_x,기준_년_코드_y,기준_분기_코드_y,상권_구분_코드,상권_코드_y,상권_코드_명_y,총_유동인구_수,개수_y
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS300015,가방,36799021,패션,8,2019,1,A,1000001,계동길,380891,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100002,중식음식점,40472439,식품,8,2019,1,A,1000001,계동길,380891,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100005,제과점,196276254,식품,8,2019,1,A,1000001,계동길,380891,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100004,양식음식점,190423119,식품,8,2019,1,A,1000001,계동길,380891,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100010,커피-음료,570413765,식품,8,2019,1,A,1000001,계동길,380891,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100005,제과점,1358849710,식품,8,2020,4,U,1001496,강남 마이스 관광특구,90836,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100004,양식음식점,2554773631,식품,8,2020,4,U,1001496,강남 마이스 관광특구,90836,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100003,일식음식점,2854854714,식품,8,2020,4,U,1001496,강남 마이스 관광특구,90836,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100002,중식음식점,5789826437,식품,8,2020,4,U,1001496,강남 마이스 관광특구,90836,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100001,한식음식점,2964219636,식품,8,2020,4,U,1001496,강남 마이스 관광특구,90836,8

In [327]:
sales_move_merge_1618 = pd.merge(s_1618, m_1618, left_index=True, right_index=True, how="inner")
sales_move_merge_1618 # 16, 17, 18년도 추정매출과 유동인구 데이터에 inner join 적용

,기준_년_코드_x,기준_분기_코드_x,상권_구분_코드_명,상권_코드_x,상권_코드_명_x,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수_x,기준_년_코드_y,기준_분기_코드_y,상권_구분_코드,상권_코드_y,상권_코드_명_y,총_유동인구_수,개수_y
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100001,한식음식점,829947947,식품,12,2016,1,A,1000001,계동길,76823,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS300002,편의점,612331303,기타,12,2016,1,A,1000001,계동길,76823,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100004,양식음식점,409659419,식품,12,2016,1,A,1000001,계동길,76823,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100008,분식전문점,150589583,식품,12,2016,1,A,1000001,계동길,76823,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS200028,미용실,40283479,미용,12,2016,1,A,1000001,계동길,76823,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300021,문구,2587842666,기타,12,2018,4,U,1001496,강남 마이스 관광특구,56902,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300017,시계및귀금속,6128891365,패션,12,2018,4,U,1001496,강남 마이스 관광특구,56902,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300024,운동/경기용품,14743701430,취미,12,2018,4,U,1001496,강남 마이스 관광특구,56902,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS100003,일식음식점,3647727740,식품,12,2018,4,U,1001496,강남 마이스 관광특구,56902,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300003,컴퓨터및주변장치판매,391255006,전자,12,2018,4,U,1001496,강남 마이스 관광특구,56902,12

In [328]:
sales_change_merge_1920 = pd.merge(s_1920, c_1920, left_index=True, right_index=True, how="inner")
sales_change_merge_1920 # 19, 20년도 추정매출과 상권변화지표 데이터에 inner join 적용

,기준_년_코드_x,기준_분기_코드_x,상권_구분_코드_명_x,상권_코드_x,상권_코드_명_x,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수_x,...,상권_구분_코드_명_y,상권_코드_y,상권_코드_명_y,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균,개수_y
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS300015,가방,36799021,패션,8,...,골목상권,1000001,계동길,LH,상권확장,88,57,107,53,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100002,중식음식점,40472439,식품,8,...,골목상권,1000001,계동길,LH,상권확장,88,57,107,53,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100005,제과점,196276254,식품,8,...,골목상권,1000001,계동길,LH,상권확장,88,57,107,53,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100004,양식음식점,190423119,식품,8,...,골목상권,1000001,계동길,LH,상권확장,88,57,107,53,8
1000001_2019_1,2019,1,골목상권,1000001,계동길,CS100010,커피-음료,570413765,식품,8,...,골목상권,1000001,계동길,LH,상권확장,88,57,107,53,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100005,제과점,1358849710,식품,8,...,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100004,양식음식점,2554773631,식품,8,...,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100003,일식음식점,2854854714,식품,8,...,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100002,중식음식점,5789826437,식품,8,...,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54,8
1001496_2020_4,2020,4,관광특구,1001496,강남 마이스 관광특구,CS100001,한식음식점,2964219636,식품,8,...,관광특구,1001496,강남 마이스 관광특구,HH,정체,125,63,114,54,8

In [329]:
sales_change_merge_1618 = pd.merge(s_1618, c_1618, left_index=True, right_index=True, how="inner")
sales_change_merge_1618 # 16, 17, 18년도 추정매출과 상권변화지표 데이터에 inner join 적용

,기준_년_코드_x,기준_분기_코드_x,상권_구분_코드_명_x,상권_코드_x,상권_코드_명_x,서비스_업종_코드,서비스_업종_코드_명,당월_매출_금액,업종_분류,개수_x,...,상권_구분_코드_명_y,상권_코드_y,상권_코드_명_y,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균,개수_y
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100001,한식음식점,829947947,식품,12,...,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS300002,편의점,612331303,기타,12,...,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100004,양식음식점,409659419,식품,12,...,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS100008,분식전문점,150589583,식품,12,...,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12
1000001_2016_1,2016,1,골목상권,1000001,계동길,CS200028,미용실,40283479,미용,12,...,골목상권,1000001,계동길,LH,상권확장,89,53,96,48,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300021,문구,2587842666,기타,12,...,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300017,시계및귀금속,6128891365,패션,12,...,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300024,운동/경기용품,14743701430,취미,12,...,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS100003,일식음식점,3647727740,식품,12,...,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12
1001496_2018_4,2018,4,관광특구,1001496,강남 마이스 관광특구,CS300003,컴퓨터및주변장치판매,391255006,전자,12,...,관광특구,1001496,강남 마이스 관광특구,LH,상권확장,93,61,102,51,12

In [ ]:
# 가공한 데이터들을 CSV 파일로 생성

In [330]:
sales_move_merge_1920.to_csv('./sales_move_merge_1920.csv', na_rep='NaN', encoding="utf-8-sig")

In [331]:
sales_move_merge_1618.to_csv('./sales_move_merge_1618.csv', na_rep="NaN", encoding="utf-8-sig")

In [333]:
sales_change_merge_1920.to_csv('./sales_change_merge_1920.csv', na_rep="NaN", encoding="utf-8-sig")

In [334]:
sales_change_merge_1618.to_csv('./sales_change_merge_1618.csv', na_rep="NaN", encoding="utf-8-sig")